### PR TITLE
README.md:add link to AUR package as optional installation method

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
If you have suggestions for any of the text I added, you might find the [insert suggestion](https://til.hashrocket.com/posts/szgdi4at59-github-insert-a-suggestion-) method useful.

**Comment by IlanFrumer** [comment]
I want to optimize the AUR PKGBUILD file.
We should first release tags of versions in git.
Then we can use `pkgver() {` to automatically fetch all available versions


https://wiki.archlinux.org/title/VCS_package_guidelines

**Comment by andy5995** [comment]
I can add you and @LangLangBart as co-maintainers. Do you already have an AUR username?

**Comment by IlanFrumer** [comment]
@andy5995 
My aur username is also ilanfrumer

**Comment by andy5995** [comment]
Added

**Comment by andy5995** [comment]
> I want to optimize the AUR PKGBUILD file. We should first release tags of versions in git. Then we can use `pkgver() {` to automatically fetch all available versions
> 
> https://wiki.archlinux.org/title/VCS_package_guidelines

It seems that using that method, and not changing the [pkgver value on L6](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=0ad-boongui), users will just get the latest version when they install the package, but they'll never be notified of an update by their package manager.

**Pull request merged**
